### ISSUE TITLE
DB Error when clicking the 'Software Administration' button in sql-ledger/admin.pl

### ISSUE THREAD

**Issue by Corvalan** [sl-community/install-sql-ledger#2]
DB Error when clicking the 'Software Administration' button in sql-ledger/admin.pl

Error!
software_administration not defined in locale/ch/admin
DB Error!

**Comment by sweitmann** [comment]
Hi Corvalan,

Thanks for your feedback on our new Ansible installation script. I will do some testing and share your input with our developers and keep you updated. 

Regards

**Comment by sweitmann** [comment]
Hi Corvalan,

Thanks for your patience. This issue only appears when installing the preconfigured SQL-Ledger on Debian 8 (Jessie). Since it works perfectly on Debian 9 (Stretch) and time is precious, we have now removed Debian 8 from the README file.

I suggest you go ahead and run it on Debian 9 (Stretch) instead. That will probably be the fastest and easiest way to get SQL-Ledger up and running.

Please feel free to contact me again if you should have any further issues. 

Regards
